// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/heyztb/lists-backend/internal/html/templates/shared"

func About() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col min-h-[100dvh]\"><header class=\"px-4 lg:px-6 h-14 flex items-center fixed top-0 left-0 right-0\"><a class=\"flex items-center justify-center\" href=\"/\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"h-6 w-6\"><path d=\"m8 3 4 8 5-5 5 15H2L8 3z\"></path></svg> <span class=\"sr-only\">Lists</span></a><nav class=\"ml-auto flex gap-4 sm:gap-6\"><a class=\"text-sm font-medium hover:underline underline-offset-4\" href=\"/login\">Log in</a> <a class=\"text-sm font-medium hover:underline underline-offset-4\" href=\"/register\">Sign up\t</a></nav></header><div class=\"w-full h-screen mx-auto my-auto py-12 lg:py-24\"><div class=\"container px-4 md:px-6\"><div class=\"flex flex-col items-center justify-center space-y-4 text-center lg:space-y-10 lg:flex-row lg:text-left lg:gap-10 xl:gap-20\"><div class=\"mx-auto max-w-sm lg:max-w-none\"><img alt=\"Author\" class=\"rounded-full\" width=\"400\" height=\"400\" src=\"/placeholder.svg\" style=\"aspect-ratio: 400 / 400; object-fit: cover;\"></div><div class=\"grid gap-2 space-y-2\"><h2 class=\"text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none\">Hi there, my name is Zach.</h2><p class=\"max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400\">I'm a software engineer from Washington state. This project was built to scratch an itch I had. This app has been carefully designed from the ground up to respect your privacy and maintain the security of your data both at rest and in transit. You can read more about it at the link below.</p><a class=\"inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors\" href=\"https://ztb.dev\">Check out the blog post</a></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = shared.Page("About").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
