// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package database

var TableNames = struct {
	GorpMigrations string
	Items          string
	Labels         string
	Lists          string
	Sections       string
	Settings       string
	Users          string
}{
	GorpMigrations: "gorp_migrations",
	Items:          "items",
	Labels:         "labels",
	Lists:          "lists",
	Sections:       "sections",
	Settings:       "settings",
	Users:          "users",
}
