// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package database

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("GorpMigrations", testGorpMigrationsUpsert)

	t.Run("Items", testItemsUpsert)

	t.Run("Labels", testLabelsUpsert)

	t.Run("Lists", testListsUpsert)

	t.Run("Sections", testSectionsUpsert)

	t.Run("Settings", testSettingsUpsert)

	t.Run("Users", testUsersUpsert)
}
