version: '3.1'
services:
  db:
    build: 
      context: .
      dockerfile: pg-Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  # remove this for production deployments
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    restart: always
    ulimits:
      memlock: -1
    ports:
      - 6379:6379
    volumes:
      - dragonflydata:/data

  lists:
    image: lists
    restart: always
    ports:
      - 4322:4322
    depends_on:
      - db
      - dragonfly
    volumes:
      - backend:/var/log/backend
    environment:
      LISTEN_ADDRESS: 0.0.0.0:8000
      DISABLE_TLS: true
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_SSL_MODE: disable
      REDIS_HOST: ${REDIS_HOST}
      PASETO_KEY: ${PASETO_KEY}
      LOG_FILE_PATH: ${LOG_FILE_PATH}

volumes:
  backend:
  dragonflydata: