// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GorpMigrations string
	Lists          string
	Settings       string
	Users          string
}{
	GorpMigrations: "gorp_migrations",
	Lists:          "lists",
	Settings:       "settings",
	Users:          "users",
}
